# 第２週：データサイエンスに必要な知識{#requisite}

## データとは{#what_data}

我々は日常、データという言葉をよく見聞きする。日常語としてのデータの意味は広い。
例えば、いくつかの国語辞典で引くと、「推論の根拠となる事実、資料」という趣旨の解説がなされている。
用例.jpで「データ」を検索してみると、次のような文例に遭遇する。

[外部サイト：用例ｊｐ](http://yourei.jp){target="_blank"}

> 「先蔵爺さんのデータには「家族」欄にゆきの名と性格が記入されていた。
> 菊地秀行『トレジャー・ハンター01 エイリアン秘宝街』より引用」

>「ビジネスの世界も同様だ。管理職になると、月に二十回から三十回以上の会議に参加しなければならないというデータもある。」
> 塩田丸男『口下手は損ですか 面白い話をするための12章』より引用」

簡単のため、管理職 (executives) とは執行役員、一般職 (employees) はそれ以外としておこう。

この用例では、データは「記憶」や「情報」という程度の意味で使われている。また、ある電子辞書の広告には以下のような書かれていた。
[外部サイト：シャープ社Papyrus](https://jp.sharp/papyrus/lineup/pw-at750/contents.html){target="_blank"}


> 「逆引きスーパー大辞林と5種類〈人名､地名､作品名､季語､慣用句〉の、｢分野別小辞典｣は､スーパー大辞林のデータを元に編集された電子版の辞書機能であり、書籍版は刊行されておりません。」
> 三省堂監修 「逆引きスーパー大辞林」「5種類の分野別小辞典」

この文脈では、「データ」をコピー元（オリジナルの辞書）の原稿という意味合いで用いているようである。


一方、データサイエンスでは、データをもう少し狭い意味で考える。つまり、データを厳密に考える。
例えば、先の引用で「管理職になると、月に二十回から三十回以上の会議に参加しなければならない」とあるが、これは恐らく「聞いた話」あるいは「噂話」のことだろう。
これが、仮にデータサイエンティストの発言だとすると、少なくとも以下は前提となっている。

1. 管理職とそれ以外の社員の区別が明確になされている
2. 管理職とそれ以外の社員のそれぞれ全員、あるいは無細工に選ばれた標本（random sampling;標本については後述）について、参加する会議の回数が少なくとも1ヶ月分は記録されている
3. 管理職が毎月参加する会議の数が20回以上となる確率を求められる
4. 一般の社員が毎月参加する会議の数が20回以下となる確率を求められる


面倒なように思われるかも知れないが、少なくとも上記4つの条件が揃っていなければ、データサイエンスの立場から「管理職になると、月に二十回から三十回以上の会議に参加しなければならない」とはいえない。

＜続く＞