# 第１１週：グループワーク{#groupwork}



7月1日から班に分かれ、各班でKaggleの課題に取り組む。 


## 7月1日{#July1} 

各班ごとに以下の作業を行う。

- 自己紹介
- 連絡先の交換
- リーダの選出とメンバの役割分担
- 班としての意見交換の方法を決める（TeamsやZoom、あるいはSlackなどを推奨）

役割分担としては、リーダー、書記（作業記録や、最終提出するプレゼンファイルの作成に責任を持つ）、Kaggleでの各ページの英語説明の要約係、Kaggleのカーネル（Pythonのスクリプト）担当などが考えられるだろう（役割については、班ごとに適宜指定して構わないが、誰が何をしたかは評価の対象となる）。最終課題では、班のメンバの誰か一人のKaggleカーネルURLを提出してもらう予定である。

教室に集まるにせよ、TeamsやZoomなど遠隔形式で作業するにせよ、各班のすべてのメンバは、毎週金曜日16時20分から17時50分までは共同作業を行っており、これに参加している場合のみ「授業に出席」したとみなす。 その確認のため、**今後も毎週小テストを行う**。小テストは、班のメンバ全員が回答すること。また回答期間を翌週月曜日にしているので、注意すること。


### 7月1日の小テスト{#test_11}

小テストでは、グループワーク初回の打ち合わせについて尋ねているので回答できるよう準備をしておくこと。

- 班リーダの名前
- リーダと連絡先を交換したか
- 班メンバとの意見交換の方法を確認したか
- 次回までに作業すべき内容を確認したか
- 次に班として会合する日時を定めたか

すべてに回答できない場合、この小テストは不可となる。

## 最終課題として何をいつまでに提出すべきか{#groupwork_submit}


真っ先に取り組むべきは、Kaggleの課題を選ぶことである！ 

最終的に提出するのは取り組んだKaggle課題のうち1つについてのプレゼンテーション資料である。

最終課題として提出するプレゼンの形式は、パワーポイントか、あるいは（LaTeXなどから変換した）PDFファイルとする。
これを**指定の時刻までに（7月29日金曜日18:00）**に、manabaの所定のページに、班のリーダーがアップロードする。班リーダのアップロードをもって、班のメンバ全員が課題を提出したとみなす。



プレゼンテーションには、以下について明記されていること。いずれかが欠けていても、減点の対象となりうる（これ以外のことが追加で記載されているのは構わない）。 

 

1. タイトルページ（スライド1枚） 
2. チームメンバー一覧（実名と Kaggle User Name[ログインした際のURL末尾の表示] との対応表、スライド1枚） 
3. 取り組んだKaggle課題の要約（スライド1枚程度） 
4. 課題に対する班としての取り組み方針（役割分担について示す。**役割ごとにスライド１枚**程度） 
5. 班として立てた仮説を説明（統計グラフを含め、スライド2枚程度） 
6. 説明変数として何を選んだか、その理由はなにか（スライド2枚程度） 
7. 選んだ分析手法とその理由（スライド1枚程度） 
8. 訓練データに対する作業結果要約（スライド1枚程度） 
9. テストデータに対する作業内容要約（スライド1枚程度） 
10. Kaggleでの評価点（ダッシュボードに表示される予測精度、および順位の報告、また全体を通しての反省点など、スライド2枚程度） 


分析手法によっては、提出プレゼン資料要件5の[仮説]、6の[説明変数選択]について説明しにくいかもしれないが、その場合は、「仮説に該当する考え方」、「選択手法において何が特徴量となっているのか」などについて説明すること。特に、深層学習の手法を使う場合は、その仕組みについて、6の[説明変数選択]のスライドに説明すること（この説明は、教員向けというよりは、班のメンバ全員が手法の意味を共有することが目的である）。

たとえば、画像データに深層学習を適用する場合、画像をどのように入力データに変換するのか、あるいは入力データに非線形の変換がなされることになるが、その変換は何をしているのか、などの説明ができるはずである。

重要なのは、班のメンバ全員が、適用した手法の目的と意味を共有できていることである。当該スライドの執筆担当者は、他の班メンバに説明するつもりで丁寧に書いてください